name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 16
      uses: actions/setup-java@v4
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./jami-android/gradlew
    - name: Build with Gradle
      working-directory: ./jami-android
      run: ./gradlew assembleDebug
