name: Build APK

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [main]  # 推送代码到 main 分支时自动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用免费的 Linux 虚拟机

    steps:
      - name: 检出代码
        uses: actions/checkout@v4  # 拉取仓库代码

      - name: 设置 JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # 根据项目需求选择 JDK 版本（如 8/11/17）

      - name: 构建 APK
        run: |
          chmod +x gradlew  # 赋予 Gradle 执行权限
          ./gradlew assembleDebug  # 编译 Debug 版 APK


				# Upload with v3
				- uses: actions/upload-artifact@v3
				  with:
				    name: my-artifact
				    path: ./output

				# Download with v2/v3 (not v4+)
				- uses: actions/download-artifact@v3  # Compatible with v3 uploads
				  with:
				    name: my-artifact
				    path: ./downloaded
    
